name: Build Hedgehog
on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          pip install pyinstaller requests Pillow pdf2docx

      - name: Create EXE
        run: |
          pyinstaller --noconsole --onefile hedgehog_app.py
          # İkon hatası riskini azaltmak için ikon parametresini şimdilik çıkardık.
          # Önce programın çalıştığını görelim, sonra ikon ekleriz.

      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: Hedgehog-Windows-Package
          path: dist/hedgehog_app.exe
